version: "3.9"

services:
  fast-api:
    container_name: skin-lesion-rest-api
    build: .
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/app
    ports:
      - 80:5000
    restart: on-failure
  